# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ggw1ikRyaTAw9sk67tE2ANfupmRYjm-
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.interpolate import interp1d

#fluxo antineutrino far detector

X2 = np.loadtxt('flux-dune-antinu-FD.txt')
Flux = np.transpose(X2)

Fluxnue = Flux[1]
Fluxnumu = Flux[2]
Fluxnutau = Flux[3]
Fluxnuebar = Flux[4]
Fluxnumubar = Flux[5]
Fluxnutaubar = Flux[6]


plt.plot(Flux[0],Fluxnumubar)
plt.xlim(0,10)

def interp(x,y):
  return interp1d(x,y)

Y = Fluxnumu*1.1*1e21
X = Flux[0]

func = interp(X,Y)
Y_interp = func(X)


plt.scatter(X,Y)
plt.plot(X,Y_interp, color = 'red')
plt.xlim(0,10)
plt.ylim(1e7,1e11)
plt.yscale("log")

